# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('success', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('time_executed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Total quantity of parent order')),
                ('stock_type', models.CharField(blank=True, max_length=10)),
                ('stock_name', models.CharField(blank=True, max_length=10)),
                ('is_sell', models.BooleanField(default=True)),
                ('time_executed', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='childorder',
            name='parent_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ParentOrder'),
        ),
    ]
